### PR TITLE
Modernised the code base

### PR DESCRIPTION
**Pull request by vanruesc**
With this PR I'd like to propose a revision of the current code base of the project to make it future-proof. 

The changes are as follows:

#### package.json
 - reformatted (improved readability)
 - added a description to package.json
 - added dev dependencies (ESLint, Rollup + Babel, JIT-Grunt + Load-Grunt-Config)
 - added peer dependency (Grunt >=0.4.0, [more information](https://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#peer-dependencies))

#### Gruntfile
 - split up into ```grunt/config``` and ```grunt/tasks``` using [jit-grunt](https://github.com/shootaroo/jit-grunt) and [load-grunt-config](https://github.com/firstandthird/load-grunt-config) for improved maintainability and build performance
 - added ESLint build step
 - added Rollup build step to generate an ES5 cjs-style task from ```src/index.js``` (uses [Babel](https://github.com/rollup/rollup-plugin-babel) internally)

#### esdoc.js
 - moved to ```src/index.js```
 - minor refactoring, logic is the same as before
 - the file ```tasks/grunt-esdoc.js``` was built using the ```grunt build``` task

Please note that these changes are suggestions. I appreciate any feedback and criticism.

### CODE REVIEW

**Comment by cleversoap** [comment]
Will look at this shortly - thanks for all the effort, looks good

**Comment by vanruesc** [comment]
Thanks for your time!

If you consider merging this, you might want to first take a look at #6 since that PR directly addresses the corresponding open issue #5 while also adding the ```.gitattributes``` file.

**Comment by vanruesc** [comment]
Just added another commit in which I replaced a hard coded path in the ```rollup``` config with ```package.module```. I forgot to include this change before, sorry for the inconvenience.

**Comment by vanruesc** [comment]
A new version of grunt-eslint came out, so I went ahead and updated it.

**Comment by vanruesc** [comment]
Hi @cleversoap,

although this is starting to get a bit messy because so much time has passed, I'm still hoping for this PR to get merged. I updated ESDoc to 1.x.x and adjusted everything to work with this new major release.

Here's an overview of the changes:
 - Version requirements for dependencies have been relaxed. Minor patch and fix releases should be safe.
 - Updated ESDoc to 1.0.1
  - Removed ```publisher``` argument from ```esdoc.generate(config)```.
  - Added ```esdoc-standard-plugin``` for testing purposes. Works as expected with no further changes.

**Comment by vanruesc** [comment]
I just realised that ESDoc >= 1.0.1 no longer reports coverage results in the console. Coverage is only available when the ```esdoc-coverage-plugin``` or the ```esdoc-standard-plugin``` is used.

I fixed the coverage report by reading the coverage output json file if it exists. In case a user decides not to use the ```esdoc-coverage-plugin```, ```grunt-esdoc``` won't try to report coverage.

This change partially supersedes #4. (It doesn't include the coverage threshold feature.)

**Comment by vanruesc** [comment]
Closed in favour of #10.

**Pull request closed without merging**
